
CREATE TABLE `t_famille_emploi`
(
    `ID_FAMILLE_EMPLOI`             int(11) NOT NULL,
    `LIB_FAMILLE_EMPLOI`            varchar(150) NOT NULL,
    `REF_COMPETENCE_FAMILLE_EMPLOI` varchar(2)   NOT NULL,
    `BK_COLOR_FAMILLE_EMPLOI`       varchar(10)  NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `t_famille_emploi` (`ID_FAMILLE_EMPLOI`, `LIB_FAMILLE_EMPLOI`, `REF_COMPETENCE_FAMILLE_EMPLOI`, `BK_COLOR_FAMILLE_EMPLOI`)

VALUES (1, 'EAU POTABLE', 'EP', '#02469E'), (2, 'ASSAINISSEMENT', 'AS', '#197D00');

ALTER TABLE `t_famille_emploi` ADD PRIMARY KEY (`ID_FAMILLE_EMPLOI`);

ALTER TABLE `t_famille_emploi` MODIFY `ID_FAMILLE_EMPLOI` int(11) NOT NULL AUTO_INCREMENT;

COMMIT;
